extern const GeoLayout goalpost_geo[];
extern Lights1 goalpost_f3dlite_material_001_lights;
extern Lights1 goalpost_f3dlite_material_002_lights;
extern Vtx goalpost_Goalpost_mesh_layer_1_vtx_0[299];
extern Gfx goalpost_Goalpost_mesh_layer_1_tri_0[];
extern Vtx goalpost_Goalpost_mesh_layer_1_vtx_1[60];
extern Gfx goalpost_Goalpost_mesh_layer_1_tri_1[];
extern Gfx mat_goalpost_f3dlite_material_001[];
extern Gfx mat_goalpost_f3dlite_material_002[];
extern Gfx goalpost_Goalpost_mesh_layer_1[];
