#include "src/game/envfx_snow.h"

const GeoLayout birdslair_area_1_geo[] = {
	GEO_NODE_START(),
	GEO_OPEN_NODE(),
		GEO_TRANSLATE_NODE_WITH_DL(LAYER_OPAQUE, -200, -40, -100, birdslair_dl_Cube_mesh_layer_1),
		GEO_DISPLAY_LIST(LAYER_OPAQUE, birdslair_dl_Plane_mesh_layer_1),
		GEO_DISPLAY_LIST(LAYER_OPAQUE, birdslair_dl_Plane_001_mesh_layer_1),
		GEO_TRANSLATE_ROTATE_WITH_DL(LAYER_TRANSPARENT, -2500, 0, 2600, 0, -90, 0, birdslair_dl_Plane_002_mesh_layer_5),
		GEO_DISPLAY_LIST(LAYER_ALPHA, birdslair_dl_Plane_003_mesh_layer_4),
		GEO_TRANSLATE_NODE_WITH_DL(LAYER_ALPHA, 989, 297, 0, birdslair_dl_Plane_004_mesh_layer_4),
		GEO_DISPLAY_LIST(LAYER_OPAQUE, birdslair_dl_Plane_005_mesh_layer_1),
		GEO_DISPLAY_LIST(LAYER_OPAQUE, birdslair_dl_Plane_007_mesh_layer_1),
	GEO_CLOSE_NODE(),
	GEO_RETURN(),
};
const GeoLayout birdslair_area_1[] = {
	GEO_NODE_SCREEN_AREA(10, SCREEN_WIDTH/2, SCREEN_HEIGHT/2, SCREEN_WIDTH/2, SCREEN_HEIGHT/2),
	GEO_OPEN_NODE(),
		GEO_ZBUFFER(0),
		GEO_OPEN_NODE(),
			GEO_NODE_ORTHO(100.0000),
			GEO_OPEN_NODE(),
				GEO_BACKGROUND(BACKGROUND_ABOVE_CLOUDS, geo_skybox_main),
			GEO_CLOSE_NODE(),
		GEO_CLOSE_NODE(),
		GEO_ZBUFFER(1),
		GEO_OPEN_NODE(),
			GEO_CAMERA_FRUSTUM_WITH_FUNC(45.0000, 100, 30000, geo_camera_fov),
			GEO_OPEN_NODE(),
				GEO_CAMERA(CAMERA_MODE_8_DIRECTIONS, 0, 0, 0, 0, -100, 0, geo_camera_main),
				GEO_OPEN_NODE(),
					GEO_BRANCH(1, birdslair_area_1_geo),
					GEO_RENDER_OBJ(),
					GEO_ASM(ENVFX_MODE_NONE, geo_envfx_main),
				GEO_CLOSE_NODE(),
			GEO_CLOSE_NODE(),
		GEO_CLOSE_NODE(),
	GEO_CLOSE_NODE(),
	GEO_END(),
};
