extern const GeoLayout secretroom_area_1_geo[];
extern const GeoLayout secretroom_area_1[];
extern const Collision secretroom_area_1_collision[];
extern const MacroObject secretroom_area_1_macro_objs[];
extern Lights1 secretroom_dl_f3dlite_material_007_lights;
extern Lights1 secretroom_dl_f3dlite_material_015_lights;
extern Lights1 secretroom_dl_f3dlite_material_019_lights;
extern Lights0 secretroom_dl_f3dlite_material_016_lights;
extern Lights1 secretroom_dl_f3dlite_material_017_lights;
extern u8 secretroom_dl_SUPER_MARIO_64_184368CA_0_2_all_rgba16[];
extern u8 secretroom_dl_Intro_rgba16[];
extern Vtx secretroom_dl_Death_Plane_mesh_layer_1_vtx_0[4];
extern Gfx secretroom_dl_Death_Plane_mesh_layer_1_tri_0[];
extern Vtx secretroom_dl_Floor_mesh_layer_1_vtx_0[4];
extern Gfx secretroom_dl_Floor_mesh_layer_1_tri_0[];
extern Vtx secretroom_dl_platforms_015_mesh_layer_1_vtx_0[30];
extern Gfx secretroom_dl_platforms_015_mesh_layer_1_tri_0[];
extern Vtx secretroom_dl_Walls_mesh_layer_1_vtx_0[75];
extern Gfx secretroom_dl_Walls_mesh_layer_1_tri_0[];
extern Vtx secretroom_dl_Welcome_Wall_mesh_layer_1_vtx_0[8];
extern Gfx secretroom_dl_Welcome_Wall_mesh_layer_1_tri_0[];
extern Vtx secretroom_dl_Welcome_Wall_mesh_layer_1_vtx_1[16];
extern Gfx secretroom_dl_Welcome_Wall_mesh_layer_1_tri_1[];
extern Gfx mat_secretroom_dl_f3dlite_material_007[];
extern Gfx mat_secretroom_dl_f3dlite_material_015[];
extern Gfx mat_secretroom_dl_f3dlite_material_003[];
extern Gfx mat_revert_secretroom_dl_f3dlite_material_003[];
extern Gfx mat_secretroom_dl_f3dlite_material_019[];
extern Gfx mat_secretroom_dl_f3dlite_material_016[];
extern Gfx mat_secretroom_dl_f3dlite_material_017[];
extern Gfx secretroom_dl_Death_Plane_mesh_layer_1[];
extern Gfx secretroom_dl_Floor_mesh_layer_1[];
extern Gfx secretroom_dl_platforms_015_mesh_layer_1[];
extern Gfx secretroom_dl_Walls_mesh_layer_1[];
extern Gfx secretroom_dl_Welcome_Wall_mesh_layer_1[];
