#include "levels/secretroom/texture_include.inc.c"
#include "levels/secretroom/area_1/collision.inc.c"
#include "levels/secretroom/area_1/macro.inc.c"
#include "levels/secretroom/area_1/spline.inc.c"
#include "levels/secretroom/model.inc.c"
