#include "src/game/envfx_snow.h"

const GeoLayout trophy_yoshi_owie_geo[] = {
	GEO_NODE_START(),
	GEO_OPEN_NODE(),
		GEO_SHADOW(0, 200, 100),
		GEO_OPEN_NODE(),
			GEO_SCALE(LAYER_FORCE, 16384),
			GEO_OPEN_NODE(),
				GEO_ANIMATED_PART(LAYER_OPAQUE, 0, 0, 0, NULL),
				GEO_OPEN_NODE(),
					GEO_ANIMATED_PART(LAYER_OPAQUE, 0, 0, 0, trophy_yoshi_owie_000_offset_001_mesh_layer_1),
					GEO_OPEN_NODE(),
						GEO_DISPLAY_LIST(LAYER_TRANSPARENT, trophy_yoshi_owie_000_offset_001_mesh_layer_5),
						GEO_ANIMATED_PART(LAYER_OPAQUE, 100, 0, 0, trophy_yoshi_owie_000_offset_002_mesh_layer_1),
						GEO_OPEN_NODE(),
							GEO_DISPLAY_LIST(LAYER_TRANSPARENT, trophy_yoshi_owie_000_offset_002_mesh_layer_5),
							GEO_ANIMATED_PART(LAYER_OPAQUE, 222, 0, 0, NULL),
							GEO_OPEN_NODE(),
								GEO_ANIMATED_PART(LAYER_OPAQUE, 60, 49, 0, NULL),
								GEO_OPEN_NODE(),
									GEO_ANIMATED_PART(LAYER_OPAQUE, 0, 0, 0, trophy_yoshi_owie_000_offset_005_mesh_layer_1),
									GEO_OPEN_NODE(),
										GEO_DISPLAY_LIST(LAYER_TRANSPARENT, trophy_yoshi_owie_000_offset_005_mesh_layer_5),
									GEO_CLOSE_NODE(),
								GEO_CLOSE_NODE(),
								GEO_SWITCH_CASE(2, geo_switch_anim_state),
								GEO_OPEN_NODE(),
									GEO_NODE_START(),
									GEO_OPEN_NODE(),
										GEO_DISPLAY_LIST(LAYER_OPAQUE, trophy_yoshi_owie_000_displaylist_mesh_layer_1),
										GEO_DISPLAY_LIST(LAYER_TRANSPARENT, trophy_yoshi_owie_000_displaylist_mesh_layer_5),
									GEO_CLOSE_NODE(),
								GEO_CLOSE_NODE(),
							GEO_CLOSE_NODE(),
							GEO_ANIMATED_PART(LAYER_OPAQUE, 51, 55, 97, NULL),
							GEO_OPEN_NODE(),
								GEO_ANIMATED_PART(LAYER_OPAQUE, 0, 0, 0, trophy_yoshi_owie_000_offset_006_mesh_layer_1),
								GEO_OPEN_NODE(),
									GEO_DISPLAY_LIST(LAYER_TRANSPARENT, trophy_yoshi_owie_000_offset_006_mesh_layer_5),
									GEO_ANIMATED_PART(LAYER_OPAQUE, 74, 0, 0, trophy_yoshi_owie_000_offset_007_mesh_layer_1),
									GEO_OPEN_NODE(),
										GEO_DISPLAY_LIST(LAYER_TRANSPARENT, trophy_yoshi_owie_000_offset_007_mesh_layer_5),
										GEO_ANIMATED_PART(LAYER_OPAQUE, 69, 0, 0, trophy_yoshi_owie_000_offset_008_mesh_layer_1),
										GEO_OPEN_NODE(),
											GEO_DISPLAY_LIST(LAYER_TRANSPARENT, trophy_yoshi_owie_000_offset_008_mesh_layer_5),
										GEO_CLOSE_NODE(),
									GEO_CLOSE_NODE(),
								GEO_CLOSE_NODE(),
							GEO_CLOSE_NODE(),
							GEO_ANIMATED_PART(LAYER_OPAQUE, 51, 55, -97, NULL),
							GEO_OPEN_NODE(),
								GEO_ANIMATED_PART(LAYER_OPAQUE, 0, 0, 0, trophy_yoshi_owie_000_offset_009_mesh_layer_1),
								GEO_OPEN_NODE(),
									GEO_DISPLAY_LIST(LAYER_TRANSPARENT, trophy_yoshi_owie_000_offset_009_mesh_layer_5),
									GEO_ANIMATED_PART(LAYER_OPAQUE, 74, 0, 0, trophy_yoshi_owie_000_offset_010_mesh_layer_1),
									GEO_OPEN_NODE(),
										GEO_DISPLAY_LIST(LAYER_TRANSPARENT, trophy_yoshi_owie_000_offset_010_mesh_layer_5),
										GEO_ANIMATED_PART(LAYER_OPAQUE, 69, 0, 0, trophy_yoshi_owie_000_offset_011_mesh_layer_1),
										GEO_OPEN_NODE(),
											GEO_DISPLAY_LIST(LAYER_TRANSPARENT, trophy_yoshi_owie_000_offset_011_mesh_layer_5),
										GEO_CLOSE_NODE(),
									GEO_CLOSE_NODE(),
								GEO_CLOSE_NODE(),
							GEO_CLOSE_NODE(),
						GEO_CLOSE_NODE(),
						GEO_ANIMATED_PART(LAYER_OPAQUE, -1, 27, 95, NULL),
						GEO_OPEN_NODE(),
							GEO_ANIMATED_PART(LAYER_OPAQUE, 0, 0, 0, trophy_yoshi_owie_000_offset_012_mesh_layer_1),
							GEO_OPEN_NODE(),
								GEO_DISPLAY_LIST(LAYER_TRANSPARENT, trophy_yoshi_owie_000_offset_012_mesh_layer_5),
								GEO_ANIMATED_PART(LAYER_OPAQUE, 100, 0, 0, trophy_yoshi_owie_000_offset_013_mesh_layer_1),
								GEO_OPEN_NODE(),
									GEO_DISPLAY_LIST(LAYER_TRANSPARENT, trophy_yoshi_owie_000_offset_013_mesh_layer_5),
									GEO_ANIMATED_PART(LAYER_OPAQUE, 95, 0, 0, trophy_yoshi_owie_000_offset_014_mesh_layer_1),
									GEO_OPEN_NODE(),
										GEO_DISPLAY_LIST(LAYER_TRANSPARENT, trophy_yoshi_owie_000_offset_014_mesh_layer_5),
									GEO_CLOSE_NODE(),
								GEO_CLOSE_NODE(),
							GEO_CLOSE_NODE(),
						GEO_CLOSE_NODE(),
						GEO_ANIMATED_PART(LAYER_OPAQUE, -89, -62, 0, NULL),
						GEO_OPEN_NODE(),
							GEO_ANIMATED_PART(LAYER_OPAQUE, 0, 0, 0, trophy_yoshi_owie_000_offset_015_mesh_layer_1),
							GEO_OPEN_NODE(),
								GEO_DISPLAY_LIST(LAYER_TRANSPARENT, trophy_yoshi_owie_000_offset_015_mesh_layer_5),
							GEO_CLOSE_NODE(),
						GEO_CLOSE_NODE(),
						GEO_ANIMATED_PART(LAYER_OPAQUE, -1, 27, -95, NULL),
						GEO_OPEN_NODE(),
							GEO_ANIMATED_PART(LAYER_OPAQUE, 0, 0, 0, trophy_yoshi_owie_000_offset_016_mesh_layer_1),
							GEO_OPEN_NODE(),
								GEO_DISPLAY_LIST(LAYER_TRANSPARENT, trophy_yoshi_owie_000_offset_016_mesh_layer_5),
								GEO_ANIMATED_PART(LAYER_OPAQUE, 100, 0, 0, trophy_yoshi_owie_000_offset_017_mesh_layer_1),
								GEO_OPEN_NODE(),
									GEO_DISPLAY_LIST(LAYER_TRANSPARENT, trophy_yoshi_owie_000_offset_017_mesh_layer_5),
									GEO_ANIMATED_PART(LAYER_OPAQUE, 95, 0, 0, trophy_yoshi_owie_000_offset_018_mesh_layer_1),
									GEO_OPEN_NODE(),
										GEO_DISPLAY_LIST(LAYER_TRANSPARENT, trophy_yoshi_owie_000_offset_018_mesh_layer_5),
									GEO_CLOSE_NODE(),
								GEO_CLOSE_NODE(),
							GEO_CLOSE_NODE(),
						GEO_CLOSE_NODE(),
					GEO_CLOSE_NODE(),
				GEO_CLOSE_NODE(),
			GEO_CLOSE_NODE(),
		GEO_CLOSE_NODE(),
	GEO_CLOSE_NODE(),
	GEO_END(),
};
