extern const GeoLayout netherportal_Anim_opt1[];
extern const GeoLayout netherportal_Anim_opt2[];
extern const GeoLayout netherportal_Anim_opt3[];
extern const GeoLayout netherportal_Anim_opt4[];
extern const GeoLayout netherportal_Anim_opt5[];
extern const GeoLayout netherportal_Anim_opt6[];
extern const GeoLayout netherportal_Anim_opt7[];
extern const GeoLayout netherportal_Anim_opt8[];
extern const GeoLayout netherportal_Anim_opt9[];
extern const GeoLayout netherportal_Anim_opt10[];
extern const GeoLayout netherportal_Anim_opt11[];
extern const GeoLayout netherportal_Anim_opt12[];
extern const GeoLayout netherportal_Anim_opt13[];
extern const GeoLayout netherportal_Anim_opt14[];
extern const GeoLayout netherportal_Anim_opt15[];
extern const GeoLayout netherportal_Anim_opt16[];
extern const GeoLayout netherportal_Anim_opt17[];
extern const GeoLayout netherportal_Anim_opt18[];
extern const GeoLayout netherportal_Anim_opt19[];
extern const GeoLayout netherportal_Anim_opt20[];
extern const GeoLayout netherportal_Anim_opt21[];
extern const GeoLayout netherportal_Anim_opt22[];
extern const GeoLayout netherportal_Anim_opt23[];
extern const GeoLayout netherportal_Anim_opt24[];
extern const GeoLayout netherportal_Anim_opt25[];
extern const GeoLayout netherportal_Anim_opt26[];
extern const GeoLayout netherportal_Anim_opt27[];
extern const GeoLayout netherportal_Anim_opt28[];
extern const GeoLayout netherportal_Anim_opt29[];
extern const GeoLayout netherportal_Anim_opt30[];
extern const GeoLayout netherportal_Anim_opt31[];
extern const GeoLayout netherportal_geo[];
extern Lights1 netherportal_obsidian_lights;
extern u8 netherportal_obsidian_ci8[];
extern u8 netherportal_obsidian_pal_rgba16[];
extern u8 netherportal__1_ci8[];
extern u8 netherportal__1_pal_rgba16[];
extern u8 netherportal__2_ci8[];
extern u8 netherportal__2_pal_rgba16[];
extern u8 netherportal__3_ci8[];
extern u8 netherportal__3_pal_rgba16[];
extern u8 netherportal__4_ci8[];
extern u8 netherportal__4_pal_rgba16[];
extern u8 netherportal__5_ci8[];
extern u8 netherportal__5_pal_rgba16[];
extern u8 netherportal__6_ci8[];
extern u8 netherportal__6_pal_rgba16[];
extern u8 netherportal__7_ci8[];
extern u8 netherportal__7_pal_rgba16[];
extern u8 netherportal__8_ci8[];
extern u8 netherportal__8_pal_rgba16[];
extern u8 netherportal__9_ci8[];
extern u8 netherportal__9_pal_rgba16[];
extern u8 netherportal__10_ci8[];
extern u8 netherportal__10_pal_rgba16[];
extern u8 netherportal__11_ci8[];
extern u8 netherportal__11_pal_rgba16[];
extern u8 netherportal__12_ci8[];
extern u8 netherportal__12_pal_rgba16[];
extern u8 netherportal__13_ci8[];
extern u8 netherportal__13_pal_rgba16[];
extern u8 netherportal__14_ci8[];
extern u8 netherportal__14_pal_rgba16[];
extern u8 netherportal__15_ci8[];
extern u8 netherportal__15_pal_rgba16[];
extern u8 netherportal__16_ci8[];
extern u8 netherportal__16_pal_rgba16[];
extern u8 netherportal__17_ci8[];
extern u8 netherportal__17_pal_rgba16[];
extern u8 netherportal__18_ci8[];
extern u8 netherportal__18_pal_rgba16[];
extern u8 netherportal__19_ci8[];
extern u8 netherportal__19_pal_rgba16[];
extern u8 netherportal__20_ci8[];
extern u8 netherportal__20_pal_rgba16[];
extern u8 netherportal__21_ci8[];
extern u8 netherportal__21_pal_rgba16[];
extern u8 netherportal__22_ci8[];
extern u8 netherportal__22_pal_rgba16[];
extern u8 netherportal__23_ci8[];
extern u8 netherportal__23_pal_rgba16[];
extern u8 netherportal__24_ci8[];
extern u8 netherportal__24_pal_rgba16[];
extern u8 netherportal__25_ci8[];
extern u8 netherportal__25_pal_rgba16[];
extern u8 netherportal__26_ci8[];
extern u8 netherportal__26_pal_rgba16[];
extern u8 netherportal__27_ci8[];
extern u8 netherportal__27_pal_rgba16[];
extern u8 netherportal__28_ci8[];
extern u8 netherportal__28_pal_rgba16[];
extern u8 netherportal__29_ci8[];
extern u8 netherportal__29_pal_rgba16[];
extern u8 netherportal__30_ci8[];
extern u8 netherportal__30_pal_rgba16[];
extern u8 netherportal__31_ci8[];
extern u8 netherportal__31_pal_rgba16[];
extern u8 netherportal__32_ci8[];
extern u8 netherportal__32_pal_rgba16[];
extern Vtx netherportal_Portal_mesh_layer_1_vtx_0[48];
extern Gfx netherportal_Portal_mesh_layer_1_tri_0[];
extern Vtx netherportal_Portal_mesh_layer_5_vtx_0[4];
extern Gfx netherportal_Portal_mesh_layer_5_tri_0[];
extern Gfx mat_netherportal_obsidian[];
extern Gfx mat_revert_netherportal_obsidian[];
extern Gfx mat_netherportal__1[];
extern Gfx mat_revert_netherportal[];
extern Gfx mat_netherportal__2[];
extern Gfx mat_netherportal__3[];
extern Gfx mat_netherportal__4[];
extern Gfx mat_netherportal__5[];
extern Gfx mat_netherportal__6[];
extern Gfx mat_netherportal__7[];
extern Gfx mat_netherportal__8[];
extern Gfx mat_netherportal__9[];
extern Gfx mat_netherportal__10[];
extern Gfx mat_netherportal__11[];
extern Gfx mat_netherportal__12[];
extern Gfx mat_netherportal__13[];
extern Gfx mat_netherportal__14[];
extern Gfx mat_netherportal__15[];
extern Gfx mat_netherportal__16[];
extern Gfx mat_netherportal__17[];
extern Gfx mat_netherportal__18[];
extern Gfx mat_netherportal__19[];
extern Gfx mat_netherportal__20[];
extern Gfx mat_netherportal__21[];
extern Gfx mat_netherportal__22[];
extern Gfx mat_netherportal__23[];
extern Gfx mat_netherportal__24[];
extern Gfx mat_netherportal__25[];
extern Gfx mat_netherportal__26[];
extern Gfx mat_netherportal__27[];
extern Gfx mat_netherportal__28[];
extern Gfx mat_netherportal__29[];
extern Gfx mat_netherportal__30[];
extern Gfx mat_netherportal__31[];
extern Gfx mat_netherportal__32[];
extern Gfx netherportal_Portal_mesh_layer_1[];
extern Gfx netherportal_Portal_mesh_layer_1_mat_override__32_30[];
extern Gfx netherportal_Portal_mesh_layer_5[];
extern Gfx netherportal_Portal_mesh_layer_5_mat_override__2_0[];
extern Gfx netherportal_Portal_mesh_layer_5_mat_override__3_1[];
extern Gfx netherportal_Portal_mesh_layer_5_mat_override__4_2[];
extern Gfx netherportal_Portal_mesh_layer_5_mat_override__5_3[];
extern Gfx netherportal_Portal_mesh_layer_5_mat_override__6_4[];
extern Gfx netherportal_Portal_mesh_layer_5_mat_override__7_5[];
extern Gfx netherportal_Portal_mesh_layer_5_mat_override__8_6[];
extern Gfx netherportal_Portal_mesh_layer_5_mat_override__9_7[];
extern Gfx netherportal_Portal_mesh_layer_5_mat_override__10_8[];
extern Gfx netherportal_Portal_mesh_layer_5_mat_override__11_9[];
extern Gfx netherportal_Portal_mesh_layer_5_mat_override__12_10[];
extern Gfx netherportal_Portal_mesh_layer_5_mat_override__13_11[];
extern Gfx netherportal_Portal_mesh_layer_5_mat_override__14_12[];
extern Gfx netherportal_Portal_mesh_layer_5_mat_override__15_13[];
extern Gfx netherportal_Portal_mesh_layer_5_mat_override__16_14[];
extern Gfx netherportal_Portal_mesh_layer_5_mat_override__17_15[];
extern Gfx netherportal_Portal_mesh_layer_5_mat_override__18_16[];
extern Gfx netherportal_Portal_mesh_layer_5_mat_override__19_17[];
extern Gfx netherportal_Portal_mesh_layer_5_mat_override__20_18[];
extern Gfx netherportal_Portal_mesh_layer_5_mat_override__21_19[];
extern Gfx netherportal_Portal_mesh_layer_5_mat_override__22_20[];
extern Gfx netherportal_Portal_mesh_layer_5_mat_override__23_21[];
extern Gfx netherportal_Portal_mesh_layer_5_mat_override__24_22[];
extern Gfx netherportal_Portal_mesh_layer_5_mat_override__25_23[];
extern Gfx netherportal_Portal_mesh_layer_5_mat_override__26_24[];
extern Gfx netherportal_Portal_mesh_layer_5_mat_override__27_25[];
extern Gfx netherportal_Portal_mesh_layer_5_mat_override__28_26[];
extern Gfx netherportal_Portal_mesh_layer_5_mat_override__29_27[];
extern Gfx netherportal_Portal_mesh_layer_5_mat_override__30_28[];
extern Gfx netherportal_Portal_mesh_layer_5_mat_override__31_29[];
extern Gfx netherportal_Portal_mesh_layer_5_mat_override__32_30[];
