extern const GeoLayout stonewall_geo[];
extern Lights1 stonewall_f3dlite_material_062_lights;
extern Lights1 stonewall_f3dlite_material_lights;
extern u8 stonewall_dark_stars_ci8[];
extern u8 stonewall_dark_stars_pal_rgba16[];
extern u8 stonewall_dark_bricks_ci8[];
extern u8 stonewall_dark_bricks_pal_rgba16[];
extern Vtx stonewall_Cube_001_mesh_layer_1_vtx_0[16];
extern Gfx stonewall_Cube_001_mesh_layer_1_tri_0[];
extern Vtx stonewall_Cube_001_mesh_layer_1_vtx_1[8];
extern Gfx stonewall_Cube_001_mesh_layer_1_tri_1[];
extern Gfx mat_stonewall_f3dlite_material_062[];
extern Gfx mat_revert_stonewall_f3dlite_material_062[];
extern Gfx mat_stonewall_f3dlite_material[];
extern Gfx mat_revert_stonewall_f3dlite_material[];
extern Gfx stonewall_Cube_001_mesh_layer_1[];
