extern const GeoLayout hell_area_1_geo[];
extern const GeoLayout hell_area_1[];
extern const Collision hell_area_1_collision[];
extern const MacroObject hell_area_1_macro_objs[];
extern Lights1 hell_dl_death_lights;
extern Lights1 hell_dl_Ground_001_lights;
extern Lights1 hell_dl_Lava_lights;
extern Lights1 hell_dl_f3dlite_material_lights;
extern u8 hell_dl__4AD98B2A_c_ci8[];
extern u8 hell_dl__4AD98B2A_c_pal_rgba16[];
extern u8 hell_dl__273462A4_c_ci8[];
extern u8 hell_dl__273462A4_c_pal_rgba16[];
extern u8 hell_dl__2FDFA86D_c_ci8[];
extern u8 hell_dl__2FDFA86D_c_pal_rgba16[];
extern Vtx hell_dl_Death_plane_mesh_layer_5_vtx_0[12];
extern Gfx hell_dl_Death_plane_mesh_layer_5_tri_0[];
extern Vtx hell_dl_Landing_spot_mesh_layer_1_vtx_0[40];
extern Gfx hell_dl_Landing_spot_mesh_layer_1_tri_0[];
extern Vtx hell_dl_Lava_mesh_layer_1_vtx_0[4];
extern Gfx hell_dl_Lava_mesh_layer_1_tri_0[];
extern Vtx hell_dl_Path_1_mesh_layer_1_vtx_0[104];
extern Gfx hell_dl_Path_1_mesh_layer_1_tri_0[];
extern Vtx hell_dl_Path_2_mesh_layer_1_vtx_0[72];
extern Gfx hell_dl_Path_2_mesh_layer_1_tri_0[];
extern Vtx hell_dl_Path_2_mesh_layer_1_vtx_1[64];
extern Gfx hell_dl_Path_2_mesh_layer_1_tri_1[];
extern Gfx mat_hell_dl_death[];
extern Gfx mat_hell_dl_Ground_001[];
extern Gfx mat_revert_hell_dl_Ground_001[];
extern Gfx mat_hell_dl_Lava[];
extern Gfx mat_revert_hell_dl_Lava[];
extern Gfx mat_hell_dl_f3dlite_material[];
extern Gfx mat_revert_hell_dl_f3dlite_material[];
extern Gfx hell_dl_Death_plane_mesh_layer_5[];
extern Gfx hell_dl_Landing_spot_mesh_layer_1[];
extern Gfx hell_dl_Lava_mesh_layer_1[];
extern Gfx hell_dl_Path_1_mesh_layer_1[];
extern Gfx hell_dl_Path_2_mesh_layer_1[];
extern Gfx hell_dl_material_revert_render_settings[];
