extern const GeoLayout lava_geo[];
extern Lights1 lava_f3dlite_material_001_lights;
extern u8 lava_LLL_ci8[];
extern u8 lava_LLL_pal_rgba16[];
extern Vtx lava_Plane_mesh_layer_1_vtx_0[4];
extern Gfx lava_Plane_mesh_layer_1_tri_0[];
extern Gfx mat_lava_f3dlite_material_001[];
extern Gfx mat_revert_lava_f3dlite_material_001[];
extern Gfx lava_Plane_mesh_layer_1[];
extern Gfx lava_material_revert_render_settings[];
